version: '3'
services:
  backend:
    build: backend/
    volumes:
      - type: bind
        source: ./backend/api
        target: /project/api
    ports:
      - 80:80
  
  frontend:
    build: frontend/
    ports:
      - 3000:3000
# TODO:コンテナ破棄時にデータを残しておく必要性があるなら、volumnsを追加したほうがいいかも
  db:
    build: db_mysql/
    container_name: myproject1_db
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - TZ="Asia/Tokyo"
    volumes:
      - myproject1_db_data:/var/lib/mysql
    ports:
      - 33306:3306
    command: --default-authentication-plugin=mysql_native_password
volumes:
  myproject1_db_data: